apiVersion: v1
kind: Namespace
metadata:
  name: eugene-ai
  labels:
    app.kubernetes.io/name: eugene-ai
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
