apiVersion: v1
kind: Service
metadata:
  name: eugene-api
  namespace: eugene-ai
spec:
  type: ClusterIP
  selector:
    app: eugene-api
  ports:
    - name: http
      port: 8000
      targetPort: http
